apiVersion: v1
kind: Service
metadata:
  name: sf-app-service
spec:
  selector:
    app: sf-app
  ports:
    - port: 80
      targetPort: 3000 # Same as containerPort in Deployment
  #     nodePort: 30009
  # type: NodePort # Use  LoadBalancer for cloud providers that support it