apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;

            server_name api.k8s.portal.seaflux.dev;

            location / {
                proxy_pass http://sf-app-service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            access_log /var/log/nginx/sf-app-access.log;
            error_log /var/log/nginx/sf-app-error.log;
        }
    }